name: flutter_ecommerce
description: A simple e-commerce app with Flutter, Riverpod & Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # State Management
  flutter_riverpod: ^2.5.1

  # UI
  google_fonts: ^6.2.1

  # File picking for image upload
  file_picker: ^8.1.2

  # HTTP
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true