// File generated by FlutterFire CLI.
// Run: flutterfire configure
// Replace this file with your actual generated firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  // ⚠️  REPLACE these values with your actual Firebase project config
  // from: Firebase Console → Project Settings → Your apps
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBJgV0pqqXbKK3Ok2byZMJfyVuNq-OZxmw",
    authDomain: "voltex-app-fdbd5.firebaseapp.com",
    projectId: "voltex-app-fdbd5",
    storageBucket: "voltex-app-fdbd5.firebasestorage.app",
    messagingSenderId: "1079519988046",
    appId: "1:1079519988046:web:d6ba03d612194bebef761f",
    measurementId: "G-5C4Y0WLECJ"
  );
}